#SingleInstance,Force

prepareFirstLine_andBackup_gitignore()


MsgBox, `n`n (line:%A_LineNumber%) `n`n`n The end of the file has been reached or there was a problem
Reload


Loop,9999
{
	FileReadLine, thisLine , .gitignore, %A_Index%
	if ErrorLevel
		break
	
	newString .= RegExReplace(thisLine,"^(\!(\w+)\/\*\*)$", "!$2`n$1") "`n"
}
MsgBox, '%newString%' = newString `n`n (line:%A_LineNumber%) `n`n`n The end of the file has been reached or there was a problem
Reload



;/¯¯¯¯ prepareAndBackup_gitignore ¯¯ 190311141110 ¯¯ 11.03.2019 14:11:10 ¯¯\
prepareFirstLine_andBackup_gitignore(){
	firstLine := "# not recomandet to edit this file, becouse this file is generated by: " A_ScriptName
	FileReadLine, thisLine , .gitignore, 1
	if(firstLine <> thisLine){
		FileRead, content , .gitignore
		tempFileAddress := ".gitignore" A_TickCount ".temp." A_ThisFunc ".txt"
		FileAppend, % firstLine "`n", % tempFileAddress
		FileAppend, % content, % tempFileAddress
		FileCopy,% tempFileAddress, .gitignore, 1
	; Sleep,200
	; FileDelete,% tempFileAddress
	}
}
;\____ prepareAndBackup_gitignore __ 190311141114 __ 11.03.2019 14:11:14 __/
